version: "3.9"

services:
  redis:
    container_name: redis
    restart: always
    image: redis
    ports:
      - "6379:6379"

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: Todo
    command: python manage.py runserver
    volumes:
      - .:/app
    ports:
      - "8000:8000"
#    environment:
#      - SECRET_KEY=django-insecure-%u6*!rq0u($@i%xez@(&z4^f0l1228#m1s0w+_)abx$ij9%iaa
#      - DEBUG=True
#
    depends_on:
      - redis

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
      - backend

#  smtp4dev:
#    image: rnwood/smtp4dev:v3
#    restart: always
#    ports:
#      # Change the number before : to the port the web interface should be accessible on
#      - '5000:80'
#      # Change the number before : to the port the SMTP server should be accessible on
#      - '25:25'
#      # Change the number before : to the port the IMAP server should be accessible on
#      - '143:143'
#    volumes:
#      # This is where smtp4dev stores the database..
#      - smtp4dev-data:/smtp4dev
#    environment:
#
#      - ServerOptions__HostName=smtp4dev
#
#  volumes:
#    smtp4dev-data:
